---
controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_velocities:
      type: velocity_controllers/JointGroupVelocityController

    robot_broadcaster:
      type: pose_broadcaster/PoseBroadcaster

    target_broadcaster:
      type: pose_broadcaster/PoseBroadcaster
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
joint_velocities:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

robotiq_gripper_controller:
  ros__parameters:
    joint: rq_robotiq_85_left_knuckle_joint
    command_interfaces: [position]
    state_interfaces:   [position]
    gripper_closed_threshold: 0.8
    goal_tolerance: 0.01
    stall_velocity_threshold: 0.002
    stall_timeout: 1.0
    allow_stalling: false

robot_broadcaster:
  ros__parameters:
    pose_name: "robot_sensor"
    publish_rate: 1.0
    frame_id: "base_link"
    tf:
      enable: true

target_broadcaster:
  ros__parameters:
    pose_name: "target_sensor"
    publish_rate: 1.0
    frame_id: "base_link"
    tf:
      enable: true

